source 'https://rubygems.org'
ruby '2.3.0'

gem 'sinatra',         '1.4.7', :require => 'sinatra/base'
gem 'rake',            '11.2.2'
gem 'thin',            '1.7.0'
gem 'abstract_method', '1.2.1'
gem 'colorize',        '0.7.7'
gem 'awesome_print',   '1.6.1'
gem 'concord',         '0.1.5'
gem 'http',            '~> 2.0'
gem 'anima',           '0.3.0'
gem 'dotenv',          '2.1.1'
gem 'sequel',          '4.37.0'
gem 'pg',              '0.18.4'
gem 'shotgun',         '0.9.1'

gem 'webmock',         '2.1.0'
gem 'rack-test',       '0.6.3'
gem 'rspec',           '~> 3.5'
gem 'reek',            '~> 4.1'
gem 'rubocop-rspec',   git: 'https://github.com/nevir/rubocop-rspec'
gem 'mutant-rspec',    git: 'https://github.com/mbj/mutant.git'

gem 'rubocop',         '>= 0.42'
gem 'guard',           '2.13.0'
gem 'guard-rspec',     '4.6.4'
