source 'https://rubygems.org'

gem 'abstract_method',  '1.2.1'
gem 'rspec',            '3.5.0',  :require => 'spec'
gem 'fuubar',           '2.0.0'
gem 'colorize',         '0.7.7'
gem 'awesome_print',    '1.6.1'
gem 'concord',          '0.1.5'
gem 'guard',            '2.13.0'
gem 'guard-rspec',      '4.6.4',  :require => false
gem 'http',             '~> 2.0'
gem 'anima',            '0.3.0'
gem 'rubocop',          '>= 0.42'
gem 'rubocop-rspec',    git: 'https://github.com/nevir/rubocop-rspec'
gem 'reek',             '~> 4.1'
gem 'mutant-rspec',     git: 'https://github.com/mbj/mutant.git'
gem 'webmock',          '2.1.0'
